apiVersion: v1
kind: Secret
metadata:
    name: db-secrets
type: Opaque
data:
    dbuser: YWRtaW4=
    dbpassword: N0sxZXcjekQwZW5M
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age102l3223us8mes8r0zw57ddax29ktuk0e8kg9yen3sgg3wlmdhgps4cgw4s
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBoYkJlY3JDalBTcDJMWUMy
            SXpueURyS1M3TXRTb2RFN3hpRmdQVHpjeUFRCkJUZHBKSll1VjRRTjlhb3NKZVha
            bXQySk12aDM1aW5EWitLR0F1M1p1NFUKLS0tIHIrZXlyN3VhRVNYd2FGZXl1dHFX
            amgvV2c0cmZmOHBzUWc4ZUlsUTl6akEKdrTWvCWhrE2jEmRoMkGnPiVMIThkRvii
            i4dYB8nhCwL98xyYNoag6Do5dXNup8jUocLr3O3cvuWDNR6QZLzjsw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-10-16T04:39:36Z"
    mac: ENC[AES256_GCM,data:LvqOyHXmQVvpyhHHxucGLTyB8lSTc2pVTa7cByCioDZyKu3okvNjGvG4ZkTJ584ElBa9WJPhYnCuqofawXdpQAhxBZ+FSV+gvjbWWw8lipZ9wdKZTEs+3dOag2qwYwyySgG3Sk5Ngl9bafdeveNfQD8RE/iUYPvezY1CSt+OlsE=,iv:YA4GnHZqcJXB5j/w+4509I+uBprU6mYwj/Er1ZekoCk=,tag:yz3uP2MXUQbGe80ZhXiHbg==,type:str]
    pgp: []
    encrypted_regex: Ë†(data|stringData)$
    version: 3.9.1
