apiVersion: v1
kind: Secret
metadata:
    name: db-secrets
type: Opaque
data:
    dbuser: ENC[AES256_GCM,data:hRvI1DE=,iv:9X4c0m4dw/cfv3XkELvEEv3ITdrApT4CYBBojjqIrYA=,tag:WeTYbXqDMmvZetR6SY6HcA==,type:str]
    dbpassword: ENC[AES256_GCM,data:7RSW9N+EjHu2,iv:i6sx6HcG+1IWqNf6DkKy6Lbd/02EDauR/v7jx9Gh0rc=,tag:oTsMYC4aHmIQKRcX8l55cQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age102l3223us8mes8r0zw57ddax29ktuk0e8kg9yen3sgg3wlmdhgps4cgw4s
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBqamFOZEdMaURKV0FCanVs
            SzRBZHQxMFNZdXVKWVRpbEQxUmQzVUpjUVcwCmZZTmNET0VZUHBzYVlVM0ZadVZG
            N2xHclRQSU9uWmlHc3JoU010eHJtTkEKLS0tIG1GMmY2VHVoRTE1UWtPSDhwQUFo
            dW5OSmwwaEFQUEJJdnFZTFpBbko1TjgK27zl3W2JwkZO3wvIdER7+LRDzo8Nld5+
            CrojfOeYCAxZYJH2Tq6fhNdqG3U3oIVEsqvc8JJHE3oHN7FmVICOoA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-10-16T00:01:12Z"
    mac: ENC[AES256_GCM,data:sK7orw/0z/XzjaWzXwFCIL/1+UXeaDgkQmIOdKAQCMD43LRpSbx5j5YwJ2j0B04xGuqzVL92wjHyQ13zJfo+V/UtusFPqyDW0f5dJqj2kn4j9nMkQD4tWNXUeXsqpo7fsdJ9u272iRP0MFvnJb7GkaEyd4YXLnBt3VZ0mJBxF6E=,iv:rXxiAfbCqzMvz8juNWPAE5totk97JMyv1FHJtKwAV30=,tag:xL+SMi8CXgsCbXRSWlt8Gw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.1
