apiVersion: apps/v1
kind: Deployment
metadata:
  name: arrienda-api
  namespace: arriendatufinca
spec:
  selector:
    matchLabels:
      app: arrienda-api
  replicas: 1
  template:
    metadata:
      labels:
         app: arrienda-api
    spec:
      imagePullSecrets:
         - name: github-secret
      containers:
         - name: estudiante
           image: localhost:5000/arrienda_tu_finca:latest
           ports:
              - containerPort: 8080
           
---
apiVersion: v1
kind: Service
metadata:
  name: arrienda-api
  namespace: arriendatufinca
spec:
  selector:
    app: estudiante
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
