apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: arrienda-ingress
  namespace: arriendatufinca
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$2
    nginx.ingress.kubernetes.io/use-regex: "true"
spec:
  ingressClassName: nginx
  rules:
    - host: arriendatufinca.local
      http:
        paths:
          - path: /api/v3(/|$)(.*)
            pathType: Prefix
            backend:
              service:
                name: arrienda-api
                port:
                  number: 8090
          - path: /(.*)
            pathType: Prefix
            backend:
              service:
                name: arrienda-frontend
                port:
                  number: 4200